name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install alsa and udev
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
    - name: Configure Cargo cache
      uses: actions/cache@v3
      with:
        path: |
          ./target
          ~/.cargo                        
        key: debug-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          debug-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-
          debug-${{ runner.os }}-
    - name: Build
      run: cargo build --release --verbose
  
  fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: FMT
      run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install alsa and udev
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
    - name: install-clippy
      run: rustup component add clippy
    - name: clippy
      run: cargo clippy -- -W clippy::all -W clippy::nursery --deny "warnings"